# Based on the example at:
# https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html

language: shell

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels 'intel'
  - conda create --name ase --file requirements.txt

script:
  - conda activate ase
  - python PtAu.py
